### ISSUE TITLE
download the dataset

### ISSUE THREAD

**Issue by 46159100** [koukou10/lstm-fcn#1]
Hi Koukou
How do I download the dataset
I get an error when I use these commands

!wget https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
!wget https://www.dropbox.com/s/6f9s6x6gp63l88p/TwoLeadECG_TEST?dl=0

--2021-08-18 17:13:28--  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 98.159.108.57
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:13:50--  (try: 2)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:14:13--  (try: 3)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:14:37--  (try: 4)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:15:02--  (try: 5)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:15:28--  (try: 6)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:15:55--  (try: 7)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:16:23--  (try: 8)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:16:52--  (try: 9)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:17:22--  (try:10)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:17:53--  (try:11)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:18:24--  (try:12)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:18:55--  (try:13)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:19:26--  (try:14)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:19:57--  (try:15)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:20:28--  (try:16)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:20:59--  (try:17)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:21:30--  (try:18)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:22:01--  (try:19)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Retrying.

--2021-08-18 17:22:32--  (try:20)  https://www.dropbox.com/s/2av4nr10v4m2vqi/TwoLeadECG_TRAIN?dl=0
Connecting to www.dropbox.com (www.dropbox.com)|98.159.108.57|:443... failed: Unknown error.
Giving up.

**Comment by koukou10** [comment]
Hi, 

It's my fault, I've changed the changed the files location on my Dropbox without committing to the repository the new links to the datasets.
Now, It' all good.
